# travis-ci
os: linux
dist: xenial
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev

script:
  # Check info.xml schema validity
  - xmllint NativeWorkflowTemplate.xsd.xml --schema NativeWorkflowTemplate.xsd --noout
  - xmllint UniversalActivity.xsd.xml --schema UniversalActivity.xsd --noout
  - xmllint UniversalShipment.xsd.xml --schema UniversalShipment.xsd --noout
