# travis-ci
os: linux
dist: xenial
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev

script:
  # Check info.xml schema validity
  - xmllint tests/NativeWorkflowTemplate.xsd.xml --schema src/NativeWorkflowTemplate.xsd --noout
  - xmllint tests/UniversalActivity.xsd.xml --schema src/UniversalActivity.xsd --noout
  - xmllint tests/UniversalShipment.xsd.xml --schema src/UniversalShipment.xsd --noout
